"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Activity, BarChart3, CalendarRange, CheckCircle2, CircleUserRound, Cog, Film, LayoutDashboard, LogOut, MessageSquareText, Plus, Radio, Settings, Users, Video } from "lucide-react";
import { Brand } from "./brand";
import { apiClient } from "@/lib/api-client";
import type { Analytics, EventData, Paginated, Poll, Question, Recording, Registration, Room, Session, Speaker, User } from "@/lib/api-types";

type Tab = "overview" | "events" | "agenda" | "participants" | "stream" | "interactions" | "recordings" | "analytics" | "settings";

const nav: Array<{ id: Tab; label: string; icon: typeof Activity }> = [
  { id: "overview", label: "Visão geral", icon: LayoutDashboard }, { id: "events", label: "Eventos", icon: CalendarRange },
  { id: "agenda", label: "Programação", icon: Activity }, { id: "participants", label: "Participantes", icon: Users },
  { id: "stream", label: "Transmissão", icon: Video }, { id: "interactions", label: "Interações", icon: MessageSquareText },
  { id: "recordings", label: "Gravações", icon: Film }, { id: "analytics", label: "Analytics", icon: BarChart3 },
  { id: "settings", label: "Configurações", icon: Settings },
];

export function OrganizerDashboard({ initialEventId, initialTab = "overview" }: { initialEventId?: string; initialTab?: Tab }) {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null); const [events, setEvents] = useState<EventData[]>([]);
  const [activeId, setActiveId] = useState(initialEventId ?? ""); const [tab, setTab] = useState<Tab>(initialTab);
  const [rooms, setRooms] = useState<Room[]>([]); const [speakers, setSpeakers] = useState<Speaker[]>([]); const [sessions, setSessions] = useState<Session[]>([]);
  const [registrations, setRegistrations] = useState<Registration[]>([]); const [recordings, setRecordings] = useState<Recording[]>([]);
  const [questions, setQuestions] = useState<Question[]>([]); const [polls, setPolls] = useState<Poll[]>([]); const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const activeEvent = useMemo(() => events.find((item) => item.id === activeId) ?? null, [events, activeId]);

  const loadResources = useCallback(async (eventId: string) => {
    const [roomData, speakerData, sessionData, registrationData, recordingData, analyticsData] = await Promise.all([
      apiClient<Paginated<Room>>(`rooms/?event=${eventId}`), apiClient<Paginated<Speaker>>(`speakers/?event=${eventId}`),
      apiClient<Paginated<Session>>(`sessions/?event=${eventId}`), apiClient<Paginated<Registration>>(`registrations/?event=${eventId}`),
      apiClient<Paginated<Recording>>(`recordings/?event=${eventId}`), apiClient<Analytics>(`events/${eventId}/analytics/`),
    ]);
    setRooms(roomData.results); setSpeakers(speakerData.results); setSessions(sessionData.results); setRegistrations(registrationData.results); setRecordings(recordingData.results); setAnalytics(analyticsData);
    if (roomData.results[0]) {
      const [questionData, pollData] = await Promise.all([apiClient<Paginated<Question>>(`questions/?room=${roomData.results[0].id}`), apiClient<Paginated<Poll>>(`polls/?room=${roomData.results[0].id}`)]);
      setQuestions(questionData.results); setPolls(pollData.results);
    } else { setQuestions([]); setPolls([]); }
  }, []);

  useEffect(() => {
    async function load() {
      try {
        const me = await fetch("/api/auth/me"); if (!me.ok) { router.push("/entrar?next=/painel"); return; }
        const activeUser = await me.json() as User;
        if (activeUser.account_type !== "organizer" && !activeUser.is_staff) { router.push("/"); return; }
        setUser(activeUser);
        const eventData = await apiClient<Paginated<EventData>>("events/?managed=true"); setEvents(eventData.results);
        const selected = initialEventId && eventData.results.some((item) => item.id === initialEventId) ? initialEventId : eventData.results[0]?.id;
        if (selected) { setActiveId(selected); await loadResources(selected); }
      } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar o painel."); }
      finally { setLoading(false); }
    }
    load();
  }, [initialEventId, loadResources, router]);

  async function reload(message?: string) { if (!activeId) return; await loadResources(activeId); if (message) { setNotice(message); window.setTimeout(() => setNotice(""), 3500); } }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.push("/entrar"); router.refresh(); }
  async function createSpeaker(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); const data = Object.fromEntries(new FormData(formEvent.currentTarget)); await apiClient("speakers/", { method: "POST", body: { event: activeId, name: data.name, email: data.email, bio: data.bio } }); formEvent.currentTarget.reset(); await reload("Palestrante adicionado."); }
  async function createSession(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); const data = Object.fromEntries(new FormData(formEvent.currentTarget)); await apiClient("sessions/", { method: "POST", body: { event: activeId, room: data.room || null, speakers: data.speaker ? [data.speaker] : [], title: data.title, slug: slugify(String(data.title)), description: data.description, starts_at: new Date(String(data.starts_at)).toISOString(), ends_at: new Date(String(data.ends_at)).toISOString(), status: "published", track: data.track, tags: [] } }); formEvent.currentTarget.reset(); await reload("Sessão publicada na agenda."); }
  async function createRoom(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); const data = Object.fromEntries(new FormData(formEvent.currentTarget)); const provider = String(data.provider); const config = provider === "call.zoom" ? { session_name: String(data.stream), passcode: String(data.passcode ?? "") } : provider === "livestream.youtube" ? { video_id: data.stream } : { url: data.stream }; await apiClient("rooms/", { method: "POST", body: { event: activeId, name: data.name, description: data.description, mode: data.mode, position: rooms.length, module_config: [{ type: provider, config }, { type: "chat.native", config: { volatile: false } }, { type: "question", config: { active: true, requires_moderation: true } }, { type: "poll", config: { active: true } }] } }); formEvent.currentTarget.reset(); await reload(provider === "call.zoom" ? "Sala Zoom criada e pronta para receber credenciais." : "Sala e canal de chat criados."); }
  async function createRecording(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); const data = Object.fromEntries(new FormData(formEvent.currentTarget)); await apiClient("recordings/", { method: "POST", body: { event: activeId, room: data.room || null, session: data.session || null, title: data.title, provider: data.provider, playback_url: data.playback_url, status: "available", published_at: new Date().toISOString() } }); formEvent.currentTarget.reset(); await reload("Gravação publicada."); }
  async function createPoll(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); const data = Object.fromEntries(new FormData(formEvent.currentTarget)); const created = await apiClient<Poll>("polls/", { method: "POST", body: { room: data.room, question: data.question, state: "draft", show_results_before_close: true, options: String(data.options).split("\n").filter(Boolean).map((text) => ({ text })) } }); await apiClient(`polls/${created.id}/transition/`, { method: "POST", body: { state: "open" } }); formEvent.currentTarget.reset(); await reload("Enquete criada e aberta."); }
  async function updateRegistration(item: Registration, status: Registration["status"]) { await apiClient(`registrations/${item.id}/`, { method: "PATCH", body: { status } }); await reload("Status da inscrição atualizado."); }
  async function moderateQuestion(item: Question, state: string) { await apiClient(`questions/${item.id}/moderate/`, { method: "POST", body: { state } }); await reload("Pergunta moderada."); }
  async function publish() { await apiClient(`events/${activeId}/publish/`, { method: "POST" }); const updated = await apiClient<Paginated<EventData>>("events/?managed=true"); setEvents(updated.results); setNotice("Evento publicado."); }
  async function saveSettings(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); const data = Object.fromEntries(new FormData(formEvent.currentTarget)); await apiClient(`events/${activeId}/`, { method: "PATCH", body: { name: data.name, description: data.description, registration_open: data.registration_open === "on", access_mode: data.access_mode, public_config: { ...(activeEvent?.public_config ?? {}), subtitle: data.subtitle } } }); const updated = await apiClient<Paginated<EventData>>("events/?managed=true"); setEvents(updated.results); setNotice("Configurações salvas."); }

  if (loading) return <main className="dashboard-loading"><span className="live-dot" /><p>Preparando seu painel…</p></main>;
  return <main className="dashboard"><aside className="dashboard-sidebar"><Brand href="/painel" /><nav className="dashboard-nav" aria-label="Navegação do painel">{nav.map(({ id, label, icon: Icon }) => <button className={tab === id ? "active" : ""} key={id} onClick={() => setTab(id)} title={label}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="dashboard-user"><span className="avatar">{user?.first_name?.slice(0, 1) || "U"}</span><div><strong>{user?.name || user?.username}</strong><br /><span className="dashboard-user-role">Organizador</span></div><button className="sidebar-logout" onClick={logout} aria-label="Sair"><LogOut size={16} /></button></div></aside><section className="dashboard-main">
    <header className="dashboard-topbar"><div><h1>{tabTitle(tab)}</h1><p>{activeEvent ? activeEvent.name : "Crie seu primeiro evento para começar."}</p></div><div className="inline-actions">{events.length > 0 && <label className="event-switcher"><span className="sr-only">Evento atual</span><select value={activeId} onChange={async (event) => { setActiveId(event.target.value); await loadResources(event.target.value); }}>{events.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}<Link className="button button-primary" href="/painel/eventos/novo"><Plus size={16} /> Novo evento</Link></div></header>
    {error && <p className="form-error">{error}</p>}{notice && <p className="form-success"><CheckCircle2 size={15} /> {notice}</p>}
    {!activeEvent && <EmptyEvents />}
    {activeEvent && tab === "overview" && <Overview event={activeEvent} analytics={analytics} sessions={sessions} recordings={recordings} rooms={rooms} onNavigate={setTab} onPublish={publish} />}
    {tab === "events" && <EventsPanel events={events} activeId={activeId} onSelect={async (id) => { setActiveId(id); setTab("overview"); await loadResources(id); }} />}
    {activeEvent && tab === "agenda" && <AgendaPanel rooms={rooms} speakers={speakers} sessions={sessions} createSpeaker={createSpeaker} createSession={createSession} />}
    {activeEvent && tab === "participants" && <ParticipantsPanel items={registrations} update={updateRegistration} />}
    {activeEvent && tab === "stream" && <StreamPanel rooms={rooms} createRoom={createRoom} />}
    {activeEvent && tab === "interactions" && <InteractionsPanel rooms={rooms} questions={questions} polls={polls} createPoll={createPoll} moderate={moderateQuestion} />}
    {activeEvent && tab === "recordings" && <RecordingsPanel rooms={rooms} sessions={sessions} recordings={recordings} create={createRecording} />}
    {activeEvent && tab === "analytics" && <AnalyticsPanel data={analytics} />}
    {activeEvent && tab === "settings" && <SettingsPanel event={activeEvent} save={saveSettings} publish={publish} />}
  </section></main>;
}

function Overview({ event, analytics, sessions, recordings, rooms, onNavigate, onPublish }: { event: EventData; analytics: Analytics | null; sessions: Session[]; recordings: Recording[]; rooms: Room[]; onNavigate: (tab: Tab) => void; onPublish: () => Promise<void> }) { const published = event.status === "published"; const hasZoom = rooms.some((room) => room.zoom_session); const stats = [{ label: "Inscritos", value: analytics?.registrations ?? 0, icon: Users }, { label: "Pessoas únicas", value: analytics?.unique_viewers ?? 0, icon: Radio }, { label: "Mensagens", value: analytics?.chat_messages ?? 0, icon: MessageSquareText }, { label: "Sessões", value: sessions.length, icon: CalendarRange }]; return <><section className="stat-grid">{stats.map(({ label, value, icon: Icon }) => <article className="stat-card" key={label}><div className="stat-card-label"><span>{label}</span><Icon size={17} /></div><strong>{value}</strong><span className="trend">dados em tempo real</span></article>)}</section><div className="dashboard-grid"><section className="dashboard-card"><div className="card-header"><div><h2>Preparação do evento</h2><span className="muted">Acompanhe o que já está configurado</span></div></div><div className="checklist"><Check label="Evento criado" done /><Check label="Agenda publicada" done={sessions.length > 0} /><Check label="Inscrições abertas" done={event.registration_open} /><Check label="Sala Zoom configurada" done={hasZoom} /><Check label="Conteúdo on-demand" done={recordings.length > 0} /><Check label="Evento publicado" done={published} /></div></section><section className="dashboard-card"><div className="card-header"><div><h2>Acesso rápido</h2><span className="muted">{published ? "Links disponíveis para o público" : "Links em prévia privada para gestores"}</span></div></div><div className="quick-links"><Link href={`/eventos/${event.slug}`} target="_blank">{published ? "Página pública" : "Pré-visualizar página"}</Link><Link href={`/eventos/${event.slug}/ao-vivo`} target="_blank">{published ? "Sala ao vivo" : "Testar sala ao vivo"}</Link>{recordings.length > 0 && <Link href={`/eventos/${event.slug}/gravacoes`} target="_blank">Gravações</Link>}{!hasZoom && <button type="button" onClick={() => onNavigate("stream")}>Configurar transmissão Zoom</button>}{!published && <button type="button" onClick={() => void onPublish()}>Publicar evento agora</button>}</div></section></div></>; }
function EventsPanel({ events, activeId, onSelect }: { events: EventData[]; activeId: string; onSelect: (id: string) => void }) { return <div className="admin-list">{events.map((event) => <article className={`admin-row${event.id === activeId ? " selected" : ""}`} key={event.id}><div><span className={`status-pill ${event.status === "published" ? "status-recorded" : "status-soon"}`}>{event.status === "published" ? "Publicado" : "Rascunho"}</span><h2>{event.name}</h2><p>{new Date(event.starts_at).toLocaleString("pt-BR")}</p></div><button className="button button-secondary" onClick={() => onSelect(event.id)}>Gerenciar</button></article>)}</div>; }
function AgendaPanel({ rooms, speakers, sessions, createSpeaker, createSession }: { rooms: Room[]; speakers: Speaker[]; sessions: Session[]; createSpeaker: (event: FormEvent<HTMLFormElement>) => void; createSession: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="admin-columns"><div><AdminSection title="Nova sessão"><form className="compact-form" onSubmit={createSession}><input name="title" placeholder="Título da sessão" required /><textarea name="description" placeholder="Descrição" /><div className="form-grid"><input name="starts_at" type="datetime-local" required /><input name="ends_at" type="datetime-local" required /><select name="room" required><option value="">Sala</option>{rooms.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select name="speaker"><option value="">Palestrante</option>{speakers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><input name="track" placeholder="Trilha" /><button className="button button-primary">Adicionar sessão</button></form></AdminSection><AdminSection title="Novo palestrante"><form className="compact-form" onSubmit={createSpeaker}><input name="name" placeholder="Nome" required /><input name="email" type="email" placeholder="E-mail" /><textarea name="bio" placeholder="Mini bio" /><button className="button button-secondary">Adicionar palestrante</button></form></AdminSection></div><AdminSection title={`Agenda · ${sessions.length} sessões`}><div className="admin-list compact">{sessions.map((item) => <article className="admin-row" key={item.id}><div><strong>{item.title}</strong><p>{new Date(item.starts_at).toLocaleString("pt-BR")} · {item.track}</p></div><span className="status-pill status-recorded">{item.status}</span></article>)}</div></AdminSection></div>; }
function ParticipantsPanel({ items, update }: { items: Registration[]; update: (item: Registration, status: Registration["status"]) => void }) { return <AdminSection title={`${items.length} participantes`}><div className="data-table"><div className="data-row data-head"><span>Participante</span><span>E-mail</span><span>Inscrição</span><span>Status</span></div>{items.map((item) => <div className="data-row" key={item.id}><strong>{item.name}</strong><span>{item.email}</span><span>{new Date(item.created_at).toLocaleDateString("pt-BR")}</span><select value={item.status} onChange={(event) => update(item, event.target.value as Registration["status"])}><option value="confirmed">Confirmada</option><option value="pending">Pendente</option><option value="cancelled">Cancelada</option><option value="blocked">Bloqueada</option></select></div>)}</div></AdminSection>; }
function StreamPanel({ rooms, createRoom }: { rooms: Room[]; createRoom: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="admin-columns"><AdminSection title="Nova sala"><form className="compact-form" onSubmit={createRoom}><input name="name" placeholder="Nome da sala" required /><textarea name="description" placeholder="Descrição" /><select name="mode" defaultValue="event"><option value="event">Evento moderado · somente convidados sobem ao palco</option><option value="meeting">Reunião · todos podem usar áudio e vídeo</option></select><select name="provider" defaultValue="call.zoom"><option value="call.zoom">Zoom Video SDK · Live Meeting</option><option value="livestream.youtube">YouTube</option><option value="livestream.vimeo">Vimeo</option><option value="livestream.iframe">Iframe</option><option value="livestream.native">HLS nativo</option></select><input name="stream" placeholder="Nome único da sessão Zoom ou ID/URL" required /><input name="passcode" maxLength={10} placeholder="Senha Zoom (opcional)" /><p className="muted compact-help">No modo evento, participantes entram como espectadores e só usam mídia após convite. No modo reunião, todos colaboram.</p><button className="button button-primary">Criar sala</button></form></AdminSection><AdminSection title="Salas configuradas"><div className="admin-list compact">{rooms.map((room) => <article className="admin-row" key={room.id}><div><strong>{room.name}</strong><p>{room.zoom_session ? `Zoom · ${room.zoom_session.session_name} · ${room.mode === "meeting" ? "reunião" : "evento"}` : room.description}</p></div><span className={`status-pill ${room.zoom_session?.configured === false ? "status-soon" : "status-recorded"}`}><Radio size={12} /> {room.zoom_session?.configured === false ? "credenciais" : "pronta"}</span></article>)}</div></AdminSection></div>; }
function InteractionsPanel({ rooms, questions, polls, createPoll, moderate }: { rooms: Room[]; questions: Question[]; polls: Poll[]; createPoll: (event: FormEvent<HTMLFormElement>) => void; moderate: (item: Question, state: string) => void }) { return <div className="admin-columns"><div><AdminSection title="Nova enquete"><form className="compact-form" onSubmit={createPoll}><select name="room" required>{rooms.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input name="question" placeholder="Pergunta" required /><textarea name="options" placeholder={'Uma opção por linha\nOpção A\nOpção B'} required /><button className="button button-primary">Criar e abrir</button></form></AdminSection><AdminSection title="Enquetes"><div className="admin-list compact">{polls.map((item) => <article className="admin-row" key={item.id}><strong>{item.question}</strong><span className="status-pill status-recorded">{item.state}</span></article>)}</div></AdminSection></div><AdminSection title="Moderação de perguntas"><div className="admin-list compact">{questions.map((item) => <article className="admin-row admin-question" key={item.id}><div><strong>{item.content}</strong><p>{item.score} votos · {item.state}</p></div><div className="inline-actions"><button className="button button-quiet" onClick={() => moderate(item, "visible")}>Aprovar</button><button className="button button-quiet" onClick={() => moderate(item, "archived")}>Arquivar</button></div></article>)}</div></AdminSection></div>; }
function RecordingsPanel({ rooms, sessions, recordings, create }: { rooms: Room[]; sessions: Session[]; recordings: Recording[]; create: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="admin-columns"><AdminSection title="Publicar gravação"><form className="compact-form" onSubmit={create}><input name="title" placeholder="Título" required /><select name="room"><option value="">Sala</option>{rooms.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select name="session"><option value="">Sessão relacionada</option>{sessions.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select><select name="provider"><option value="youtube">YouTube</option><option value="vimeo">Vimeo</option><option value="external">Externo</option></select><input name="playback_url" type="url" placeholder="URL para assistir" required /><button className="button button-primary">Publicar gravação</button></form></AdminSection><AdminSection title="Catálogo on-demand"><div className="admin-list compact">{recordings.map((item) => <article className="admin-row" key={item.id}><div><strong>{item.title}</strong><p>{item.provider}</p></div><span className="status-pill status-recorded">{item.status}</span></article>)}</div></AdminSection></div>; }
function AnalyticsPanel({ data }: { data: Analytics | null }) { if (!data) return <p className="muted">Analytics ainda indisponíveis.</p>; const max = Math.max(1, ...data.rooms.map((item) => item.visits)); return <><section className="stat-grid"><Stat label="Inscrições" value={data.registrations} /><Stat label="Confirmadas" value={data.confirmed_registrations} /><Stat label="Visitantes únicos" value={data.unique_viewers} /><Stat label="Visitas" value={data.total_visits} /></section><AdminSection title="Audiência por sala"><div className="analytics-bars">{data.rooms.map((room) => <div key={room.room_id}><div className="progress-row-top"><span>{room.room_name}</span><strong>{room.visits} visitas</strong></div><div className="progress-track"><div className="progress-fill" style={{ width: `${(room.visits / max) * 100}%` }} /></div><small>{room.chat_messages} mensagens · {room.questions} perguntas</small></div>)}</div></AdminSection></>; }
function SettingsPanel({ event, save, publish }: { event: EventData; save: (e: FormEvent<HTMLFormElement>) => void; publish: () => void }) { return <div className="admin-columns"><AdminSection title="Configuração geral"><form className="compact-form" onSubmit={save}><label className="field"><span>Nome</span><input name="name" defaultValue={event.name} required /></label><label className="field"><span>Chamada principal</span><input name="subtitle" defaultValue={String(event.public_config.subtitle ?? "")} /></label><label className="field"><span>Descrição</span><textarea name="description" defaultValue={event.description} /></label><label className="field"><span>Acesso</span><select name="access_mode" defaultValue={event.access_mode}><option value="registration">Inscrição</option><option value="public">Público</option><option value="invite">Convidados</option></select></label><label className="check-field"><input name="registration_open" type="checkbox" defaultChecked={event.registration_open} /> Inscrições abertas</label><button className="button button-primary">Salvar alterações</button></form></AdminSection><AdminSection title="Publicação"><div className="publish-card"><Cog size={28} /><h3>{event.status === "published" ? "Evento publicado" : "Pronto para publicar?"}</h3><p className="muted">A publicação libera a página pública e as inscrições.</p><button className="button button-secondary" onClick={publish}>{event.status === "published" ? "Publicar novamente" : "Publicar evento"}</button></div></AdminSection></div>; }
function AdminSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="dashboard-card admin-section"><div className="card-header"><h2>{title}</h2></div>{children}</section>; }
function Stat({ label, value }: { label: string; value: number }) { return <article className="stat-card"><div className="stat-card-label">{label}</div><strong>{value}</strong></article>; }
function Check({ label, done }: { label: string; done: boolean }) { return <div className={done ? "check-row done" : "check-row"}><CheckCircle2 size={18} /><span>{label}</span></div>; }
function EmptyEvents() { return <section className="empty-dashboard"><CircleUserRound size={42} /><h2>Seu primeiro evento começa aqui.</h2><p>Crie o evento, configure a agenda e publique quando estiver pronto.</p><Link className="button button-primary" href="/painel/eventos/novo"><Plus size={16} /> Criar evento</Link></section>; }
function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function tabTitle(tab: Tab) { return nav.find((item) => item.id === tab)?.label ?? "Painel"; }
